/**
 * @file c2a_core_sample_components.hpp
 * @brief User side components management installed on a spacecraft for C2A-CORE
 */

#ifndef S2E_SIMULATION_SPACECRAFT_C2A_CORE_SAMPLE_COMPONENTS_HPP_
#define S2E_SIMULATION_SPACECRAFT_C2A_CORE_SAMPLE_COMPONENTS_HPP_

#include <dynamics/dynamics.hpp>
#include <environment/global/global_environment.hpp>
#include <environment/local/local_environment.hpp>
#include <library/math/vector.hpp>
#include <simulation/spacecraft/installed_components.hpp>

// include for components
#include <components/examples/example_serial_communication_with_obc.hpp>
#include <components/real/cdh/on_board_computer_with_c2a.hpp>

/**
 * @class C2aCoreSampleComponents
 * @brief User side components management installed on a spacecraft for C2A-CORE
 */
class C2aCoreSampleComponents : public InstalledComponents {
 public:
  /**
   * @fn C2aCoreSampleComponents
   * @brief Constructor
   */
  C2aCoreSampleComponents(const Dynamics* dynamics, Structure* structure, const LocalEnvironment* local_environment,
                          const GlobalEnvironment* global_environment, const SimulationConfiguration* configuration, ClockGenerator* clock_generator);

  /**
   * @fn ~C2aCoreSampleComponents
   * @brief Destructor
   */
  ~C2aCoreSampleComponents();

  // Override functions for InstalledComponents
  /**
   * @fn GenerateForce_b_N
   * @brief Return force generated by components in unit Newton in body fixed frame
   */
  libra::Vector<3> GenerateForce_b_N();
  /**
   * @fn GenerateTorque_b_Nm
   * @brief Return torque generated by components in unit Newton-meter in body fixed frame
   */
  libra::Vector<3> GenerateTorque_b_Nm();
  /**
   * @fn LogSetup
   * @brief Setup the logger for components
   */
  void LogSetup(Logger& logger);

 private:
  // Components
  ObcWithC2a* obc_;  //!< Onboard Computer with C2A
  ExampleSerialCommunicationWithObc* exp_serial_communication_;

  // References
  const Dynamics* dynamics_;                      //!< Dynamics information of the spacecraft
  const Structure* structure_;                    //!< Structure information of the spacecraft
  const LocalEnvironment* local_environment_;     //!< Local environment information around the spacecraft
  const GlobalEnvironment* global_environment_;   //!< Global environment information around the spacecraft
  const SimulationConfiguration* configuration_;  //!< Simulation settings
};

#endif  // S2E_SIMULATION_SPACECRAFT_C2A_CORE_SAMPLE_COMPONENTS_HPP_
