#include "User_sat.h"
#include "User_Components.h"
#include "Initialize.h"
#include "ClockGenerator.h"

UserSat::UserSat(SimulationConfig config)
  :Spacecraft(config)
{
  Initialize();
}

UserSat::~UserSat()
{
  delete environments_;
  delete disturbances_;
  delete components_;
}

void UserSat::Initialize()
{
  environments_ = new Envir(config_.mainIniPath);
  disturbances_ = new Disturbances(config_.mainIniPath);
  components_ = new UserComponents(dynamics_, &config_);
  IniAccess mainIni = IniAccess(config_.mainIniPath);
}

void UserSat::LogSetup(Logger & logger)
{
  Spacecraft::LogSetup(logger);
  environments_->LogSetup(logger);
  disturbances_->LogSetup(logger);
  components_->CompoLogSetUp(logger);
}

void UserSat::Update()
{
  // Update Dynamics
  Spacecraft::Update();

  // Update Components
  for (int i = 0; i < config_.simTime->GetStepSec() * 1000; i++)
  {
    ClockGenerator::TickToComponents();
  }
  // Add force and torque generated by components
  dynamics_->AddTorque_b(components_->GenerateTorque_b());
  dynamics_->AddForce_b(components_->GenerateForce_b());

  // Update environment and disturbances
  environments_->Update(*this, *config_.simTime);
  disturbances_->Update(*environments_, *this);

  // Add force and torque generated by disturbances
  dynamics_->AddTorque_b(disturbances_->GetTorque());
  dynamics_->AddForce_b(disturbances_->GetForce());
}
