#include "User_sat.h"
#include "User_Components.h"
#include "Initialize.h"
#include "ClockGenerator.h"

UserSat::UserSat(SimulationConfig* sim_config, const GlobalEnvironment* glo_env, const int sat_id)
:Spacecraft(sim_config, glo_env, sat_id)
{
  Initialize(sim_config, glo_env, sat_id);
}

UserSat::~UserSat()
{
  delete components_;
}

void UserSat::Initialize(SimulationConfig* sim_config, const GlobalEnvironment* glo_env, const int sat_id)
{
  components_ = new UserComponents(dynamics_, structure_, local_env_, glo_env, sim_config, &clock_gen_, sat_id);
}

void UserSat::LogSetup(Logger & logger)
{
  Spacecraft::LogSetup(logger);
  components_->CompoLogSetUp(logger);
}

void UserSat::Update(const SimTime* sim_time)
{
  // Update Dynamics
  Spacecraft::Update(sim_time);
  // clear force and torques
  Clear();
  // Update Components
  clock_gen_.UpdateComponents(sim_time);
  // Add force and torque generated by components
  dynamics_->AddTorque_b(components_->GenerateTorque_b());
  dynamics_->AddForce_b(components_->GenerateForce_b());
}
